### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by suciptoid** [daper/key-value-conf#1]
```
$ node ./bin/www
fs.js:680
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:680:19)
    at tryReadSync (fs.js:478:20)
    at Object.fs.readFileSync (fs.js:515:19)
    at reqConfigFile (/Users/sucipto/Development/js/dicoding/slack-challenge/node_modules/key-value-conf/configuration.js:128:3
1)
    at new Configuration (/Users/sucipto/Development/js/dicoding/slack-challenge/node_modules/key-value-conf/configuration.js:1
51:13)
    at Object.<anonymous> (/Users/sucipto/Development/js/dicoding/slack-challenge/routes/index.js:6:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
error Command failed with exit code 1.
```

**Comment by daper** [comment]
Hi @showcheap! Thanks for getting me know about this bug. It's fixed in 0c3521e and v0.9.3 in NPM. Maybe it's time for a new mayor version with some changes. And method descriptions in README.
